### ISSUE TITLE
Only Font Changing (RPCS3)

### ISSUE THREAD

**Issue by cswick0717** [dylanhale/ScorebugMods#1]
The only thing changing is the font, the scorebug itself stays the same. For SEC on CBS, the CBS logo still shows up for the coin toss.

CFP 22-
![unknown_2022 12 21-01 54](https://user-images.githubusercontent.com/121153364/208841322-718f50dc-783f-4337-9ea2-b8c47dd96fa5.png)

SEC on CBS- 
![unknown_2022 12 21-01 56](https://user-images.githubusercontent.com/121153364/208841442-7090ed08-dd45-4c02-a9ce-1acf4ee8b643.png)
![unknown_2022 12 21-01 55](https://user-images.githubusercontent.com/121153364/208841454-699d981d-377e-443a-81fb-03c3b1b2c85a.png)

**Comment by dylanhale** [comment]
Looks to be an issue with your patch file not applying. Make sure to delete or move the EDAT one in the DLC folder.
