### ISSUE TITLE
It is in my root directory?

### ISSUE THREAD

**Issue by pressurin** [dylanhale/ScorebugMods#4]
![F65E1E5D-C4AB-44F1-923B-821F60B39719](https://user-images.githubusercontent.com/123086849/213457182-52c888a6-5d23-4698-a3c6-0246e61b14cd.png)
![913C59D3-0AB7-49A6-9216-C7B1D6F11502](https://user-images.githubusercontent.com/123086849/213457186-33c606fb-d55c-4d39-afba-3ac9da82fbcd.png)

**Comment by dylanhale** [comment]
Missing EBOOT.bin file which is needed to even be able to launch the base game.
