### ISSUE TITLE
Fox Scorebug Loading Screen Issue

### ISSUE THREAD

**Issue by PotatoKing5566** [dylanhale/ScorebugMods#9]
It loads the Fox Intro perfectly fine but it wont get past the Caleb Williams Loading pic.

![Screenshot 2023-11-07 223102](https://github.com/dylanhale/ScorebugMods/assets/150216064/cdc11e03-c77f-4e5b-9f2d-9e3db6cfdbe3)

![Screenshot 2023-11-07 223146](https://github.com/dylanhale/ScorebugMods/assets/150216064/34d7dfad-6b61-41f0-bc60-ccbbcd1f9a16)

**Comment by dylanhale** [comment]
This issue is caused by a corruption issue when using manual files
